# Generated by Django 4.2.25 on 2025-11-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_alter_suggestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='anonymous_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
