# Generated by Django 4.2.25 on 2025-11-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_suggestion_anonymous_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='category',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('services', 'Services'), ('programs', 'Programs'), ('safety', 'Safety'), ('environment', 'Environment'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
