# Generated by Django 4.2.25 on 2025-11-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_approved', 'role'], name='accounts_cu_is_appr_65d03b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_approved', 'role', 'is_deactivated'], name='accounts_cu_is_appr_3c323e_idx'),
        ),
    ]
