# Generated by Django 4.2.25 on 2025-11-09 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Captain AI', max_length=100)),
                ('greeting_message', models.TextField(default="Hello! I'm your Virtual Barangay Captain. How can I assist you today?")),
                ('tone', models.CharField(default='professional', help_text='professional, friendly, formal, casual', max_length=50)),
                ('language_style', models.CharField(default='mixed', help_text='english, tagalog, mixed', max_length=50)),
                ('proactive_suggestions', models.BooleanField(default=True)),
                ('ask_followup_questions', models.BooleanField(default=True)),
                ('empathy_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('system_prompt', models.TextField(default='You are a helpful Virtual Barangay Captain. You assist residents with their concerns, provide information about policies and procedures, and give personalized advice based on their situation.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Captain Personality',
                'verbose_name_plural': 'Captain Personalities',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_situation', models.TextField(blank=True, help_text="Summary of user's situation")),
                ('conversation_topic', models.CharField(blank=True, max_length=200)),
                ('satisfaction_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Captain Conversation',
                'verbose_name_plural': 'AI Captain Conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('ordinance', 'Ordinance'), ('resolution', 'Resolution'), ('procedure', 'Procedure'), ('requirement', 'Requirement'), ('guideline', 'Guideline'), ('faq', 'FAQ')], max_length=50)),
                ('content', models.TextField(help_text='Full policy content')),
                ('summary', models.TextField(help_text='Brief summary for AI context')),
                ('keywords', models.TextField(help_text='Comma-separated keywords')),
                ('ordinance_number', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('times_referenced', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Document',
                'verbose_name_plural': 'Policy Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SituationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_type', models.CharField(choices=[('complaint', 'Filing Complaint'), ('document', 'Document Request'), ('business', 'Business Permit'), ('construction', 'Construction Permit'), ('dispute', 'Neighbor Dispute'), ('emergency', 'Emergency Situation'), ('welfare', 'Social Welfare'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommended_steps', models.TextField(help_text='Step-by-step guidance')),
                ('required_documents', models.TextField(blank=True)),
                ('estimated_timeline', models.CharField(blank=True, max_length=200)),
                ('times_used', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_policies', models.ManyToManyField(blank=True, to='ai_captain.policydocument')),
            ],
            options={
                'verbose_name': 'Situation Template',
                'verbose_name_plural': 'Situation Templates',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('captain_response', models.TextField()),
                ('intent_detected', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('referenced_policies', models.TextField(blank=True, help_text='Comma-separated policy IDs')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_captain.conversation')),
            ],
            options={
                'verbose_name': 'AI Captain Message',
                'verbose_name_plural': 'AI Captain Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_detected', models.CharField(max_length=200)),
                ('advice_given', models.TextField()),
                ('policies_cited', models.TextField(blank=True)),
                ('was_accepted', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_logs', to='ai_captain.message')),
            ],
            options={
                'verbose_name': 'Advice Log',
                'verbose_name_plural': 'Advice Logs',
            },
        ),
    ]
