# Generated by Django 4.2.25 on 2025-11-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('events', 'Events'), ('urgent', 'Urgent'), ('maintenance', 'Maintenance'), ('community', 'Community')], default='general', max_length=20),
        ),
    ]
