# Generated by Django 4.2.25 on 2025-11-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'publish_date'], name='announcemen_status_f6c2cd_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', '-created_at'], name='announcemen_status_c8b2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['expiry_date'], name='announcemen_expiry__bb5922_idx'),
        ),
    ]
