# Generated by Django 4.2.25 on 2025-11-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_add_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='anonymous_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
